force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EventOrganizer__c.field-meta.xml
<CustomField>
    <fullName>EventOrganizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>EventOrganizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventAttendee__c/EventAttendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Attendee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventOrganizer__c/EventOrganizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EventOrganizer__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Event Organizers</relationshipLabel>
    <relationshipName>Event_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeEventsService.cls
public with sharing class AttendeeEventsService {
    
    @AuraEnabled(cacheable=true)
    public static List<MemberWrapper> upcomingEvents(String attendeeId) {
        List<Event__c> events = [SELECT Id, Location__c, Location__r.Name, EventOrganizer__c,
                                        EventOrganizer__r.Name, Name__c, StartDateTime__c,
                                  (SELECT Id, Name FROM Event_Attendees__r WHERE Attendee__c =: attendeeId)
                                 FROM Event__c
                                 WHERE StartDateTime__c >= TODAY
                                 AND Live__c = true
                                 WITH SECURITY_ENFORCED
                                ];

        List<MemberWrapper> memberInfo = new List<MemberWrapper>();
        for(Event__c eve : events){
            MemberWrapper wrapper = new MemberWrapper();
            wrapper.isMember = eve.Event_Attendees__r.size() > 0;
            wrapper.event = eve;
            wrapper.eventId = eve.Id;
            wrapper.eventAttendee = wrapper.isMember ? eve.Event_Attendees__r[0] : null;

            memberInfo.add(wrapper);
        }

        return memberInfo;
    }
  
    @AuraEnabled(cacheable=true)
    public static List<EventAttendee__c> pastEvents(String attendeeId) {
        return [SELECT Id, Name, Event__c, Event__r.Location__c, Event__r.Location__r.Name,
                       Event__r.EventOrganizer__c, Event__r.EventOrganizer__r.Name,
                       Event__r.Name__c, Event__r.StartDateTime__c
                FROM EventAttendee__c
                WHERE Attendee__c = :attendeeId
                AND Event__r.StartDateTime__c < TODAY
                WITH SECURITY_ENFORCED
               ];
    }

    public class MemberWrapper {

        @AuraEnabled
        public Boolean isMember;

        @AuraEnabled
        public String eventId;

        @AuraEnabled
        public EventAttendee__c eventAttendee;

        @AuraEnabled
        public Event__c event;
    }

}