force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventOrganizer__c.field-meta.xml
<CustomField>
    <fullName>EventOrganizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>EventOrganizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/MaxSeats__c.field-meta.xml
<CustomField>
    <fullName>MaxSeats__c</fullName>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventAttendee__c/EventAttendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Attendee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventOrganizer__c/EventOrganizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestEditMembershipService.cls
@isTest
private class TestEditMembershipService {
    
    @TestSetup
    static void makeData(){
        EventOrganizer__c organizer = new EventOrganizer__c(Name = 'Organizer 1',
                                                            Email__c = 'testorganizer1@test.com',
                                                            Phone__c = '234567876543'
                                                           );
        insert organizer;

        Event__c event1 = new Event__c(EventOrganizer__c = organizer.Id,
                                       Name__c = 'Test Event 1',
                                       Status__c = 'In Progress',
                                       StartDateTime__c = Datetime.now().addDays(-14),
                                       EndDateTime__c = Datetime.now().addDays(14),
                                       MaxSeats__c = 10,
                                       EventType__c = 'Virtual',
                                       Live__c = true
                                      );

        Event__c event2 = event1.clone();
        event2.Name__c = 'Test Event 2';
        event2.StartDateTime__c = Datetime.now().addDays(-7);
        event2.EndDateTime__c = Datetime.now().addMonths(3);

        Event__c event3 = event1.clone();
        event3.Name__c = 'Test Event 3';
        event3.StartDateTime__c = Datetime.now().addDays(-17);
        event3.EndDateTime__c = Datetime.now().addMonths(2);

        Attendee__c attendee = new Attendee__c(Name = 'Test Attendee',
                                               Email__c = 'testemail@ema.com.test',
                                               Phone__c = '234511176543'
                                              );

        insert new List<SObject>{event1, event2, event3, attendee};

        insert new EventAttendee__c(Event__c = event1.Id,
                                    Attendee__c = attendee.Id
                                   );
    }

    @isTest
    static void testClearMembership(){
        Attendee__c attendee = [SELECT Id FROM Attendee__c LIMIT 1];

        List<EditMembershipService.MemberWrapper> results = EditMembershipService.findEvents(attendee.Id, 'delete');
        System.assertEquals(1, results.size());

        List<String> eventIds = new List<String>{results[0].eventId};

        Boolean isSuccess = EditMembershipService.manageMembership(attendee.Id, eventIds, 'delete');
        System.assert(isSuccess);

        System.assertEquals(0, [SELECT COUNT() FROM EventAttendee__c WHERE Attendee__c = :attendee.Id]);
    }

    @isTest
    static void testAddMembership(){
        Attendee__c attendee = [SELECT Id FROM Attendee__c LIMIT 1];

        List<EditMembershipService.MemberWrapper> results = EditMembershipService.findEvents(attendee.Id, 'create');
        System.assertEquals(2, results.size());

        List<String> eventIds = new List<String>{results[0].eventId};

        Boolean isSuccess = EditMembershipService.manageMembership(attendee.Id, eventIds, 'create');
        System.assert(isSuccess);

        System.assertEquals(2, [SELECT COUNT() FROM EventAttendee__c WHERE Attendee__c = :attendee.Id]);
    }

}