force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EventOrganizer__c.field-meta.xml
<CustomField>
    <fullName>EventOrganizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>EventOrganizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/MaxSeats__c.field-meta.xml
<CustomField>
    <fullName>MaxSeats__c</fullName>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventAttendee__c/EventAttendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Attendee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventOrganizer__c/EventOrganizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestAttendeeEventsService.cls
@isTest
private class TestAttendeeEventsService {

    @isTest
    static void tester(){
        EventOrganizer__c organizer = new EventOrganizer__c(Name = 'Organizer 1',
                                                            Email__c = 'testorganizer1@test.com',
                                                            Phone__c = '234567876543'
                                                           );
        insert organizer;

        List<Event__c> events = new List<Event__c>();
        for(Integer i=1; i<=200; i++){
            events.add(new Event__c(EventOrganizer__c = organizer.Id,
                                    Name__c = 'Test Event ' + String.valueOf(i),
                                    Status__c = 'In Progress',
                                    StartDateTime__c = i<=100 ? Datetime.now().addMonths(-3) : Datetime.now().addDays(3),
                                    MaxSeats__c = 10,
                                    EventType__c = 'Virtual',
                                    Live__c = true
                                ));
        }
        
        insert events;
        
        Attendee__c attendee = new Attendee__c(Name = 'Mustafa Test',
                                               Email__c = 'test@test.com',
                                               Phone__c = '23456786543'
                                              );
        insert attendee;

        List<EventAttendee__c> eaList = new List<EventAttendee__c>();
        eaList.add(new EventAttendee__c(Event__c = events[7].Id, Attendee__c = attendee.Id));
        eaList.add(new EventAttendee__c(Event__c = events[17].Id, Attendee__c = attendee.Id));
        eaList.add(new EventAttendee__c(Event__c = events[117].Id, Attendee__c = attendee.Id));
        eaList.add(new EventAttendee__c(Event__c = events[165].Id, Attendee__c = attendee.Id));
        insert eaList;

        Test.startTest();
        List<EventAttendee__c> pastEvents = AttendeeEventsService.pastEvents(attendee.Id);
        List<AttendeeEventsService.MemberWrapper> upcomingEvents = AttendeeEventsService.upcomingEvents(attendee.Id);
        Test.stopTest();

        System.assertEquals(2, pastEvents.size());
        System.assertEquals(100, upcomingEvents.size());

        Integer memberCount = 0;
        for(AttendeeEventsService.MemberWrapper mw : upcomingEvents){
            if(mw.isMember) memberCount++;
        }

        System.assertEquals(2, memberCount);
    }

}