force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventOrganizer__c.field-meta.xml
<CustomField>
    <fullName>EventOrganizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>EventOrganizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventOrganizer__c/EventOrganizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/WsEventDetails.cls
@RestResource(urlMapping='/EventDetails/*')
global with sharing class WsEventDetails {

    // https://mshnema-dev-ed.my.salesforce.com/services/apexrest/EventDetails/
    @HttpGet
    global static List<EventWrapper> getEventDetails(){
        List<EventWrapper> events = new List<EventWrapper>();
        for(Event__c ev : [SELECT Id, Name, Name__c, StartDateTime__c, EndDateTime__c, EventType__c, EventOrganizer__r.Name
                           FROM Event__c
                           WHERE Live__c = true
                           AND StartDateTime__c >= TODAY
                           WITH SECURITY_ENFORCED
                          ])
        {
            events.add(new EventWrapper(ev));
        }

        return events;
    }

    global class EventWrapper {

        global String eventId;
        global String stdName;
        global String name;
        global String startDate;
        global Datetime endDate;
        global String eventType;
        global String organizer;

        global EventWrapper(Event__c event){
            this.eventId = String.valueOf(event.Id);
            this.stdName = event.Name;
            this.name = event.Name__c;
            this.startDate = event.StartDateTime__c.format('yyyy-MM-dd HH:mm');
            this.endDate = event.EndDateTime__c;
            this.eventType = event.EventType__c;
            this.organizer = event.EventOrganizer__r.Name;
        }

    }
    
}