force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventOrganizer__c.field-meta.xml
<CustomField>
    <fullName>EventOrganizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>EventOrganizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/MaxSeats__c.field-meta.xml
<CustomField>
    <fullName>MaxSeats__c</fullName>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOrganizer__c/EventOrganizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EventSpeaker__c/EventSpeaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{000000}</displayFormat>
        <label>Event Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventSpeaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventSpeaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestEventSpeakerHandler.cls
@isTest
private class TestEventSpeakerHandler {
    
    @testSetup
    static void prepareData(){
        EventOrganizer__c organizer = new EventOrganizer__c(Name = 'Organizer 1',
                                                            Email__c = 'testorganizer1@test.com',
                                                            Phone__c = '234567876543'
                                                           );
        insert organizer;

        Event__c event = new Event__c(EventOrganizer__c = organizer.Id,
                                      Name__c = 'Test Event',
                                      Status__c = 'In Progress',
                                      StartDateTime__c = Datetime.now().addDays(-14),
                                      EndDateTime__c = Datetime.now().addDays(14),
                                      MaxSeats__c = 10,
                                      EventType__c = 'Virtual',
                                      Live__c = true
                                     );
        insert event;

        Speaker__c spaker1 = new Speaker__c(Name = 'Speaker 1',
                                            Email__c = 'testspeaker1@test.com',
                                            Phone__c = '6543245643'
                                           );

        Speaker__c spaker2 = new Speaker__c(Name = 'Speaker 2',
                                            Email__c = 'testspeaker2@test.com',
                                            Phone__c = '4423233435'
                                           );

        insert new List<Speaker__c>{spaker1, spaker2};

        insert new EventSpeaker__c(Event__c = event.Id, Speaker__c = spaker1.Id);
    }

    @isTest
    static void testPositive(){
        EventSpeaker__c eventSpeaker = [SELECT Id, Event__c, Speaker__c FROM EventSpeaker__c LIMIT 1];

        Boolean isFailed = false;
        try {
            EventSpeaker__c newRecord = new EventSpeaker__c(Event__c = eventSpeaker.Event__c, Speaker__c = eventSpeaker.Speaker__c);
            insert newRecord;
        }catch(Exception exc){
            isFailed = true;
        }

        System.assert(isFailed);
    }

    @isTest
    static void testNegative(){
        Event__c event = [SELECT Id FROM Event__c WHERE Name__c = 'Test Event' LIMIT 1];
        Speaker__c spaker2 = [SELECT Id FROM Speaker__c WHERE Name = 'Speaker 2' LIMIT 1];

        EventSpeaker__c newRecord = new EventSpeaker__c(Event__c = event.Id, Speaker__c = spaker2.Id);
        insert newRecord;

        System.assertNotEquals(newRecord.Id, null);
    }

    @isTest
    static void testBulk(){
        
    }

}